### ISSUE TITLE
GetNewAddress(account string) (cashutil.Address, error) return err

### ISSUE THREAD

**Issue by miss201** [copernet/whc.go#15]
用的wormhole版本是0.2.2，在测试环境下，调用SDK的这方法报错？
	cli := NewRPCInstance()
	add, err := cli.GetNewAddress("u5")
	if err != nil {
		log.Fatal(err)
	}
fmt.Printf("%s,%v \n","newaddress:"+add.String())

输出结果：2018/12/06 10:35:28 empty address content

  addList,err :=cli.GetAddressesByAccount("u5")
	if err != nil{
		log.Fatal(err)
	}
	fmt.Printf("%s,%v","addlist",addList)
输出结果：2018/12/06 10:45:45 empty address content

**Comment by qshuai** [comment]
@miss201 preparing a patch for this issue. Thanks!
